spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.23:8848
  rabbitmq:
    host: 192.168.187.146
    port: 5672
    username: root
    password: 123456
  application:
    name: rqbbitmq-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/information?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password:
mq:
  config:
    queue: queue.email
server:
  port: 8001
