server:
  port: 2555
email:
  username: yqy6@foxmail.com
  passward: cyqntslzqarzdjdj
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.23:8848
  application:
    name: service-email