server:
  port: 8071
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.23:8848
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/information?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: